### ISSUE TITLE
Prettier resets changes with efm

### ISSUE THREAD

**Issue by gowep** [lukastl21/dotfiles#3]
Hello,

I found your dotfiles while setting up neovim with efm.
You use a BufWritePost autocmd, while I use a BufWritePre autocmd. I do this because otherwise I would have to save twice for the changes to be comitted and because the neovim lsp docs recommend it.
When I use your prettier settings, when a changed Markdown file is saved, the changes get discarded and only then formatted.
Do you have any pointer how to fix it?

**Comment by gowep** [comment]
I managed to fix it thanks to one of your comments on an issue by reading from stdin.
Does efm work for you if you open two different go files at once? In that case efm and gopls attach to both files for me but linters and formatters of efm only work in the first one while gopls works in all buffers.

**Comment by lukas-reineke** [comment]
> You use a BufWritePost autocmd, while I use a BufWritePre autocmd. I do this because otherwise I would have to save twice for the changes to be comitted and because the neovim lsp docs recommend it.

I use `BufWritePost` because I have a custom format handler to format asynchronously.
If you use `BufWritePre`, you have to use `vim.lsp.buf.formatting_sync()` and wait until formatting is done before you can do anything else.

I use `vim.lsp.buf.formatting()`, and in the handler do the formatting once I get the response from the server, if it is save to do so.
https://github.com/lukas-reineke/dotfiles/blob/3b95081bef8fa84fc12dc2977fd805b90b3af4f1/vim/lua/lsp/handlers.lua#L1-L14

This makes saving feel a lot faster, because it doesn't freeze Neovim.

> In that case efm and gopls attach to both files for me but linters and formatters of efm only work in the first one while gopls works in all buffers.

Not sure about this. It works fine for me. You should look into your LSP log and see what is happening (you get the path like this `:lua print(vim.lsp.get_log_path())`)

**Comment by gowep** [comment]
There was nothing in the LSP log, but I found the problem by removing stuff from your dotfiles until it stopped working.
The missing setting was `vim.cmd [[filetype plugin indent on]]`. For some reason i thought it was set by default in neovim.
